version: '3.8'
services:
 flask_api:
  build:
   context: .
  ports:
  - 6060:6060
  environment:
    FLASK_ENV: development
  volumes:
  - ./:/app
  - /home/hbi/project_api/python_flask/data_AWS:/data_AWS